// This is a generated file, please see: gen_functional_c_types.js

#ifndef IFC_SCHEMA_H
#define IFC_SCHEMA_H

#include <stdint.h>
#include <stddef.h>
#include <web-ifc/schema/ifc-schema.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  LOGICAL_FALSE = 0,
  LOGICAL_TRUE = 1,
  LOGICAL_UNKNOWN = 2
} logical;

// static inline const char* schemas_to_string(IFC_SCHEMA s) {
//   switch (s) {
//     case IFC2X3: return "IFC2X3";
//     case IFC4: return "IFC4";
//     case IFC4X3: return "IFC4X3";
//     default: return "Unknown";
//   }
// }

typedef struct { size_t off, len; } Slice;

static const char* SCHEMA_NAME_DATA[] = { "IFC2X3", "IFC2X_FINAL", "IFC4", "IFC4X3", "IFC4X1", "IFC4X2", "IFC4X3_RC3", "IFC4X3_RC4", "IFC4X3_RC1", "IFC4X3_RC2", "IFC4X3_ADD2", "IFC4X3_ADD1" };
static const Slice SCHEMA_NAME_INDEX[] = { {0,2}, {2,1}, {3,9} };
static const size_t SCHEMA_NAME_ROWS = sizeof(SCHEMA_NAME_INDEX) / sizeof(SCHEMA_NAME_INDEX[0]);
static inline const char* get_schema_name(size_t r, size_t c) { return SCHEMA_NAME_DATA[ SCHEMA_NAME_INDEX[r].off + c ]; }

typedef struct { size_t number; void* value; } IFC2X3_IfcComplexNumber;
typedef struct { size_t number; void* value; } IFC2X3_IfcCompoundPlaneAngleMeasure;
typedef struct { size_t type; void* data; } IFC2X3_IfcActionSourceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcActionTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcActuatorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAddressTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAheadOrBehind;
typedef struct { size_t type; void* data; } IFC2X3_IfcAirTerminalBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAirTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAirToAirHeatRecoveryTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAlarmTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAnalysisModelTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAnalysisTheoryTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcArithmeticOperatorEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcAssemblyPlaceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcBSplineCurveForm;
typedef struct { size_t type; void* data; } IFC2X3_IfcBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcBenchmarkEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcBoilerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcBooleanOperator;
typedef struct { size_t type; void* data; } IFC2X3_IfcBuildingElementProxyTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCableCarrierFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCableCarrierSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCableSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcChangeActionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcChillerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCoilTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcColumnTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCompressorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCondenserTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcConstraintEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcControllerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCooledBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCoolingTowerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCostScheduleTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCoveringTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCurrencyEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcCurtainWallTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDamperTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDataOriginEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDerivedUnitEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDimensionExtentUsage;
typedef struct { size_t type; void* data; } IFC2X3_IfcDirectionSenseEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDistributionChamberElementTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDocumentConfidentialityEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDocumentStatusEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDoorPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDoorPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDoorStyleConstructionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDoorStyleOperationEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDuctFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDuctSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcDuctSilencerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricCurrentEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricDistributionPointFunctionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricFlowStorageDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricGeneratorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricHeaterTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricMotorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElectricTimeControlTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElementAssemblyTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcElementCompositionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcEnergySequenceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcEnvironmentalImpactCategoryEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcEvaporativeCoolerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcEvaporatorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFanTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFilterTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFireSuppressionTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFlowDirectionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFlowInstrumentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFlowMeterTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcFootingTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcGasTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcGeometricProjectionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcGlobalOrLocalEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcHeatExchangerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcHumidifierTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcInternalOrExternalEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcInventoryTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcJunctionBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLampTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLayerSetDirectionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLightDistributionCurveEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLightEmissionSourceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLightFixtureTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLoadGroupTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcLogicalOperatorEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcMotorConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcNullStyle;
typedef struct { size_t type; void* data; } IFC2X3_IfcObjectTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcObjectiveEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcOccupantTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcOutletTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPermeableCoveringOperationEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPhysicalOrVirtualEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPileConstructionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPileTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPipeFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPipeSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPlateTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProcedureTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProfileTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProjectOrderRecordTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProjectOrderTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProjectedOrTrueLengthEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPropertySourceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcProtectiveDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcPumpTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRailingTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRampFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRampTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcReflectanceMethodEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcReinforcingBarRoleEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcReinforcingBarSurfaceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcResourceConsumptionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRibPlateDirectionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRoleEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcRoofTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSIPrefix;
typedef struct { size_t type; void* data; } IFC2X3_IfcSIUnitName;
typedef struct { size_t type; void* data; } IFC2X3_IfcSanitaryTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSectionTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSensorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSequenceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcServiceLifeFactorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcServiceLifeTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSlabTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSoundScaleEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSpaceHeaterTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSpaceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStackTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStairFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStairTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStateEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStructuralCurveTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcStructuralSurfaceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSurfaceSide;
typedef struct { size_t type; void* data; } IFC2X3_IfcSurfaceTextureEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcSwitchingDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTankTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTendonTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTextPath;
typedef struct { size_t type; void* data; } IFC2X3_IfcThermalLoadSourceEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcThermalLoadTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTimeSeriesDataTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTimeSeriesScheduleTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTransformerTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTransitionCode;
typedef struct { size_t type; void* data; } IFC2X3_IfcTransportElementTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcTrimmingPreference;
typedef struct { size_t type; void* data; } IFC2X3_IfcTubeBundleTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcUnitEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcUnitaryEquipmentTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcValveTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcVibrationIsolatorTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWallTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWasteTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWindowPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWindowPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWindowStyleConstructionEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWindowStyleOperationEnum;
typedef struct { size_t type; void* data; } IFC2X3_IfcWorkControlTypeEnum;
typedef struct { void* data; } IFC2X3_IfcActorSelect;
typedef struct { void* data; } IFC2X3_IfcAppliedValueSelect;
typedef struct { void* data; } IFC2X3_IfcAxis2Placement;
typedef struct { void* data; } IFC2X3_IfcBooleanOperand;
typedef struct { void* data; } IFC2X3_IfcCharacterStyleSelect;
typedef struct { void* data; } IFC2X3_IfcClassificationNotationSelect;
typedef struct { void* data; } IFC2X3_IfcColour;
typedef struct { void* data; } IFC2X3_IfcColourOrFactor;
typedef struct { void* data; } IFC2X3_IfcConditionCriterionSelect;
typedef struct { void* data; } IFC2X3_IfcCsgSelect;
typedef struct { void* data; } IFC2X3_IfcCurveFontOrScaledCurveFontSelect;
typedef struct { void* data; } IFC2X3_IfcCurveOrEdgeCurve;
typedef struct { void* data; } IFC2X3_IfcCurveStyleFontSelect;
typedef struct { void* data; } IFC2X3_IfcDateTimeSelect;
typedef struct { void* data; } IFC2X3_IfcDefinedSymbolSelect;
typedef struct { void* data; } IFC2X3_IfcDerivedMeasureValue;
typedef struct { void* data; } IFC2X3_IfcDocumentSelect;
typedef struct { void* data; } IFC2X3_IfcDraughtingCalloutElement;
typedef struct { void* data; } IFC2X3_IfcFillAreaStyleTileShapeSelect;
typedef struct { void* data; } IFC2X3_IfcFillStyleSelect;
typedef struct { void* data; } IFC2X3_IfcGeometricSetSelect;
typedef struct { void* data; } IFC2X3_IfcHatchLineDistanceSelect;
typedef struct { void* data; } IFC2X3_IfcLayeredItem;
typedef struct { void* data; } IFC2X3_IfcLibrarySelect;
typedef struct { void* data; } IFC2X3_IfcLightDistributionDataSourceSelect;
typedef struct { void* data; } IFC2X3_IfcMaterialSelect;
typedef struct { void* data; } IFC2X3_IfcMeasureValue;
typedef struct { void* data; } IFC2X3_IfcMetricValueSelect;
typedef struct { void* data; } IFC2X3_IfcObjectReferenceSelect;
typedef struct { void* data; } IFC2X3_IfcOrientationSelect;
typedef struct { void* data; } IFC2X3_IfcPointOrVertexPoint;
typedef struct { void* data; } IFC2X3_IfcPresentationStyleSelect;
typedef struct { void* data; } IFC2X3_IfcShell;
typedef struct { void* data; } IFC2X3_IfcSimpleValue;
typedef struct { void* data; } IFC2X3_IfcSizeSelect;
typedef struct { void* data; } IFC2X3_IfcSpecularHighlightSelect;
typedef struct { void* data; } IFC2X3_IfcStructuralActivityAssignmentSelect;
typedef struct { void* data; } IFC2X3_IfcSurfaceOrFaceSurface;
typedef struct { void* data; } IFC2X3_IfcSurfaceStyleElementSelect;
typedef struct { void* data; } IFC2X3_IfcSymbolStyleSelect;
typedef struct { void* data; } IFC2X3_IfcTextFontSelect;
typedef struct { void* data; } IFC2X3_IfcTextStyleSelect;
typedef struct { void* data; } IFC2X3_IfcTrimmingSelect;
typedef struct { void* data; } IFC2X3_IfcUnit;
typedef struct { void* data; } IFC2X3_IfcValue;
typedef struct { void* data; } IFC2X3_IfcVectorOrDirection;
typedef struct { size_t number; void* value; } IFC4_IfcArcIndex;
typedef struct { size_t number; void* value; } IFC4_IfcComplexNumber;
typedef struct { size_t number; void* value; } IFC4_IfcCompoundPlaneAngleMeasure;
typedef struct { size_t number; void* value; } IFC4_IfcLineIndex;
typedef struct { size_t number; void* value; } IFC4_IfcPropertySetDefinitionSet;
typedef struct { size_t type; void* data; } IFC4_IfcActionRequestTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcActionSourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcActionTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcActuatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAddressTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAirTerminalBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAirTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAirToAirHeatRecoveryTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAlarmTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAnalysisModelTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAnalysisTheoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcArithmeticOperatorEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAssemblyPlaceEnum;
typedef struct { size_t type; void* data; } IFC4_IfcAudioVisualApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBSplineCurveForm;
typedef struct { size_t type; void* data; } IFC4_IfcBSplineSurfaceForm;
typedef struct { size_t type; void* data; } IFC4_IfcBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBenchmarkEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBoilerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBooleanOperator;
typedef struct { size_t type; void* data; } IFC4_IfcBuildingElementPartTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBuildingElementProxyTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBuildingSystemTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcBurnerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCableCarrierFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCableCarrierSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCableFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCableSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcChangeActionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcChillerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcChimneyTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCoilTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcColumnTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCommunicationsApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcComplexPropertyTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCompressorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCondenserTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcConstraintEnum;
typedef struct { size_t type; void* data; } IFC4_IfcConstructionEquipmentResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcConstructionMaterialResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcConstructionProductResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcControllerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCooledBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCoolingTowerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCostItemTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCostScheduleTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCoveringTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCrewResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCurtainWallTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcCurveInterpolationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDamperTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDataOriginEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDerivedUnitEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDirectionSenseEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDiscreteAccessoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDistributionChamberElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDistributionPortTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDistributionSystemEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDocumentConfidentialityEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDocumentStatusEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorStyleConstructionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorStyleOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDoorTypeOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDuctFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDuctSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcDuctSilencerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricDistributionBoardTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricFlowStorageDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricGeneratorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricMotorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElectricTimeControlTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElementAssemblyTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcElementCompositionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcEngineTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcEvaporativeCoolerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcEvaporatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcEventTriggerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcEventTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcExternalSpatialElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFanTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFastenerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFilterTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFireSuppressionTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFlowDirectionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFlowInstrumentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFlowMeterTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFootingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcFurnitureTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcGeographicElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcGeometricProjectionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcGlobalOrLocalEnum;
typedef struct { size_t type; void* data; } IFC4_IfcGridTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcHeatExchangerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcHumidifierTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcInterceptorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcInternalOrExternalEnum;
typedef struct { size_t type; void* data; } IFC4_IfcInventoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcJunctionBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcKnotType;
typedef struct { size_t type; void* data; } IFC4_IfcLaborResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLampTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLayerSetDirectionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLightDistributionCurveEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLightEmissionSourceEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLightFixtureTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLoadGroupTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcLogicalOperatorEnum;
typedef struct { size_t type; void* data; } IFC4_IfcMechanicalFastenerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcMedicalDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcMotorConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcNullStyle;
typedef struct { size_t type; void* data; } IFC4_IfcObjectTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcObjectiveEnum;
typedef struct { size_t type; void* data; } IFC4_IfcOccupantTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcOpeningElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcOutletTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPerformanceHistoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPermeableCoveringOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPermitTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPhysicalOrVirtualEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPileConstructionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPileTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPipeFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPipeSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPlateTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPreferredSurfaceCurveRepresentation;
typedef struct { size_t type; void* data; } IFC4_IfcProcedureTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProfileTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProjectOrderTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProjectedOrTrueLengthEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProjectionElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPropertySetTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProtectiveDeviceTrippingUnitTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcProtectiveDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcPumpTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRailingTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRampFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRampTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRecurrenceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcReflectanceMethodEnum;
typedef struct { size_t type; void* data; } IFC4_IfcReinforcingBarRoleEnum;
typedef struct { size_t type; void* data; } IFC4_IfcReinforcingBarSurfaceEnum;
typedef struct { size_t type; void* data; } IFC4_IfcReinforcingBarTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcReinforcingMeshTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRoleEnum;
typedef struct { size_t type; void* data; } IFC4_IfcRoofTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSIPrefix;
typedef struct { size_t type; void* data; } IFC4_IfcSIUnitName;
typedef struct { size_t type; void* data; } IFC4_IfcSanitaryTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSensorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSequenceEnum;
typedef struct { size_t type; void* data; } IFC4_IfcShadingDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSimplePropertyTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSlabTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSolarDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSpaceHeaterTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSpaceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSpatialZoneTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStackTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStairFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStairTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStateEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStructuralCurveActivityTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStructuralCurveMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStructuralSurfaceActivityTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcStructuralSurfaceMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSubContractResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSurfaceFeatureTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSurfaceSide;
typedef struct { size_t type; void* data; } IFC4_IfcSwitchingDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcSystemFurnitureElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTankTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTaskDurationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTaskTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTendonAnchorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTendonTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTextPath;
typedef struct { size_t type; void* data; } IFC4_IfcTimeSeriesDataTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTransformerTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTransitionCode;
typedef struct { size_t type; void* data; } IFC4_IfcTransportElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcTrimmingPreference;
typedef struct { size_t type; void* data; } IFC4_IfcTubeBundleTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcUnitEnum;
typedef struct { size_t type; void* data; } IFC4_IfcUnitaryControlElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcUnitaryEquipmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcValveTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcVibrationIsolatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcVoidingFeatureTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWallTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWasteTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowStyleConstructionEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowStyleOperationEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWindowTypePartitioningEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWorkCalendarTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWorkPlanTypeEnum;
typedef struct { size_t type; void* data; } IFC4_IfcWorkScheduleTypeEnum;
typedef struct { void* data; } IFC4_IfcActorSelect;
typedef struct { void* data; } IFC4_IfcAppliedValueSelect;
typedef struct { void* data; } IFC4_IfcAxis2Placement;
typedef struct { void* data; } IFC4_IfcBendingParameterSelect;
typedef struct { void* data; } IFC4_IfcBooleanOperand;
typedef struct { void* data; } IFC4_IfcClassificationReferenceSelect;
typedef struct { void* data; } IFC4_IfcClassificationSelect;
typedef struct { void* data; } IFC4_IfcColour;
typedef struct { void* data; } IFC4_IfcColourOrFactor;
typedef struct { void* data; } IFC4_IfcCoordinateReferenceSystemSelect;
typedef struct { void* data; } IFC4_IfcCsgSelect;
typedef struct { void* data; } IFC4_IfcCurveFontOrScaledCurveFontSelect;
typedef struct { void* data; } IFC4_IfcCurveOnSurface;
typedef struct { void* data; } IFC4_IfcCurveOrEdgeCurve;
typedef struct { void* data; } IFC4_IfcCurveStyleFontSelect;
typedef struct { void* data; } IFC4_IfcDefinitionSelect;
typedef struct { void* data; } IFC4_IfcDerivedMeasureValue;
typedef struct { void* data; } IFC4_IfcDocumentSelect;
typedef struct { void* data; } IFC4_IfcFillStyleSelect;
typedef struct { void* data; } IFC4_IfcGeometricSetSelect;
typedef struct { void* data; } IFC4_IfcGridPlacementDirectionSelect;
typedef struct { void* data; } IFC4_IfcHatchLineDistanceSelect;
typedef struct { void* data; } IFC4_IfcLayeredItem;
typedef struct { void* data; } IFC4_IfcLibrarySelect;
typedef struct { void* data; } IFC4_IfcLightDistributionDataSourceSelect;
typedef struct { void* data; } IFC4_IfcMaterialSelect;
typedef struct { void* data; } IFC4_IfcMeasureValue;
typedef struct { void* data; } IFC4_IfcMetricValueSelect;
typedef struct { void* data; } IFC4_IfcModulusOfRotationalSubgradeReactionSelect;
typedef struct { void* data; } IFC4_IfcModulusOfSubgradeReactionSelect;
typedef struct { void* data; } IFC4_IfcModulusOfTranslationalSubgradeReactionSelect;
typedef struct { void* data; } IFC4_IfcObjectReferenceSelect;
typedef struct { void* data; } IFC4_IfcPointOrVertexPoint;
typedef struct { void* data; } IFC4_IfcPresentationStyleSelect;
typedef struct { void* data; } IFC4_IfcProcessSelect;
typedef struct { void* data; } IFC4_IfcProductRepresentationSelect;
typedef struct { void* data; } IFC4_IfcProductSelect;
typedef struct { void* data; } IFC4_IfcPropertySetDefinitionSelect;
typedef struct { void* data; } IFC4_IfcResourceObjectSelect;
typedef struct { void* data; } IFC4_IfcResourceSelect;
typedef struct { void* data; } IFC4_IfcRotationalStiffnessSelect;
typedef struct { void* data; } IFC4_IfcSegmentIndexSelect;
typedef struct { void* data; } IFC4_IfcShell;
typedef struct { void* data; } IFC4_IfcSimpleValue;
typedef struct { void* data; } IFC4_IfcSizeSelect;
typedef struct { void* data; } IFC4_IfcSolidOrShell;
typedef struct { void* data; } IFC4_IfcSpaceBoundarySelect;
typedef struct { void* data; } IFC4_IfcSpecularHighlightSelect;
typedef struct { void* data; } IFC4_IfcStructuralActivityAssignmentSelect;
typedef struct { void* data; } IFC4_IfcStyleAssignmentSelect;
typedef struct { void* data; } IFC4_IfcSurfaceOrFaceSurface;
typedef struct { void* data; } IFC4_IfcSurfaceStyleElementSelect;
typedef struct { void* data; } IFC4_IfcTextFontSelect;
typedef struct { void* data; } IFC4_IfcTimeOrRatioSelect;
typedef struct { void* data; } IFC4_IfcTranslationalStiffnessSelect;
typedef struct { void* data; } IFC4_IfcTrimmingSelect;
typedef struct { void* data; } IFC4_IfcUnit;
typedef struct { void* data; } IFC4_IfcValue;
typedef struct { void* data; } IFC4_IfcVectorOrDirection;
typedef struct { void* data; } IFC4_IfcWarpingStiffnessSelect;
typedef struct { size_t number; void* value; } IFC4X3_IfcArcIndex;
typedef struct { size_t number; void* value; } IFC4X3_IfcComplexNumber;
typedef struct { size_t number; void* value; } IFC4X3_IfcCompoundPlaneAngleMeasure;
typedef struct { size_t number; void* value; } IFC4X3_IfcLineIndex;
typedef struct { size_t number; void* value; } IFC4X3_IfcPropertySetDefinitionSet;
typedef struct { size_t type; void* data; } IFC4X3_IfcActionRequestTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcActionSourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcActionTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcActuatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAddressTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAirTerminalBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAirTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAirToAirHeatRecoveryTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAlarmTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAlignmentCantSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAlignmentHorizontalSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAlignmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAlignmentVerticalSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAnalysisModelTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAnalysisTheoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAnnotationTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcArithmeticOperatorEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAssemblyPlaceEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcAudioVisualApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBSplineCurveForm;
typedef struct { size_t type; void* data; } IFC4X3_IfcBSplineSurfaceForm;
typedef struct { size_t type; void* data; } IFC4X3_IfcBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBearingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBenchmarkEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBoilerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBooleanOperator;
typedef struct { size_t type; void* data; } IFC4X3_IfcBridgePartTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBridgeTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBuildingElementPartTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBuildingElementProxyTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBuildingSystemTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBuiltSystemTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcBurnerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCableCarrierFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCableCarrierSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCableFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCableSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCaissonFoundationTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcChangeActionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcChillerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcChimneyTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCoilTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcColumnTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCommunicationsApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcComplexPropertyTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCompressorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCondenserTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConstraintEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConstructionEquipmentResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConstructionMaterialResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConstructionProductResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcControllerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcConveyorSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCooledBeamTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCoolingTowerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCostItemTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCostScheduleTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCourseTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCoveringTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCrewResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCurtainWallTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcCurveInterpolationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDamperTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDataOriginEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDerivedUnitEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDirectionSenseEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDiscreteAccessoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDistributionBoardTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDistributionChamberElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDistributionPortTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDistributionSystemEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDocumentConfidentialityEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDocumentStatusEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDoorPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDoorPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDoorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDoorTypeOperationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDuctFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDuctSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcDuctSilencerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEarthworksCutTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEarthworksFillTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricDistributionBoardTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricFlowStorageDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricFlowTreatmentDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricGeneratorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricMotorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElectricTimeControlTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElementAssemblyTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcElementCompositionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEngineTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEvaporativeCoolerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEvaporatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEventTriggerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcEventTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcExternalSpatialElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFacilityPartCommonTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFacilityUsageEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFanTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFastenerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFilterTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFireSuppressionTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFlowDirectionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFlowInstrumentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFlowMeterTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFootingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcFurnitureTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcGeographicElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcGeometricProjectionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcGeotechnicalStratumTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcGlobalOrLocalEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcGridTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcHeatExchangerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcHumidifierTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcImpactProtectionDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcInterceptorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcInternalOrExternalEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcInventoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcJunctionBoxTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcKerbTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcKnotType;
typedef struct { size_t type; void* data; } IFC4X3_IfcLaborResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLampTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLayerSetDirectionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLightDistributionCurveEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLightEmissionSourceEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLightFixtureTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLiquidTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLoadGroupTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcLogicalOperatorEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMarineFacilityTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMarinePartTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMechanicalFastenerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMedicalDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMobileTelecommunicationsApplianceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMooringDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcMotorConnectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcNavigationElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcObjectiveEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcOccupantTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcOpeningElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcOutletTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPavementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPerformanceHistoryTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPermeableCoveringOperationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPermitTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPhysicalOrVirtualEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPileConstructionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPileTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPipeFittingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPipeSegmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPlateTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPreferredSurfaceCurveRepresentation;
typedef struct { size_t type; void* data; } IFC4X3_IfcProcedureTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProfileTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProjectOrderTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProjectedOrTrueLengthEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProjectionElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPropertySetTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProtectiveDeviceTrippingUnitTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcProtectiveDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcPumpTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRailTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRailingTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRailwayPartTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRailwayTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRampFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRampTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRecurrenceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReferentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReflectanceMethodEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReinforcedSoilTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReinforcingBarRoleEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReinforcingBarSurfaceEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReinforcingBarTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcReinforcingMeshTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRoadPartTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRoadTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRoleEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcRoofTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSIPrefix;
typedef struct { size_t type; void* data; } IFC4X3_IfcSIUnitName;
typedef struct { size_t type; void* data; } IFC4X3_IfcSanitaryTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSectionTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSensorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSequenceEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcShadingDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSignTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSignalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSimplePropertyTemplateTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSlabTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSolarDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSpaceHeaterTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSpaceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSpatialZoneTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStackTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStairFlightTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStairTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStateEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStructuralCurveActivityTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStructuralCurveMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStructuralSurfaceActivityTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcStructuralSurfaceMemberTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSubContractResourceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSurfaceFeatureTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSurfaceSide;
typedef struct { size_t type; void* data; } IFC4X3_IfcSwitchingDeviceTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcSystemFurnitureElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTankTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTaskDurationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTaskTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTendonAnchorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTendonConduitTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTendonTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTextPath;
typedef struct { size_t type; void* data; } IFC4X3_IfcTimeSeriesDataTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTrackElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTransformerTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTransitionCode;
typedef struct { size_t type; void* data; } IFC4X3_IfcTransportElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcTrimmingPreference;
typedef struct { size_t type; void* data; } IFC4X3_IfcTubeBundleTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcUnitEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcUnitaryControlElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcUnitaryEquipmentTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcValveTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcVehicleTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcVibrationDamperTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcVibrationIsolatorTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcVirtualElementTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcVoidingFeatureTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWallTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWasteTerminalTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWindowPanelOperationEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWindowPanelPositionEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWindowTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWindowTypePartitioningEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWorkCalendarTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWorkPlanTypeEnum;
typedef struct { size_t type; void* data; } IFC4X3_IfcWorkScheduleTypeEnum;
typedef struct { void* data; } IFC4X3_IfcActorSelect;
typedef struct { void* data; } IFC4X3_IfcAppliedValueSelect;
typedef struct { void* data; } IFC4X3_IfcAxis2Placement;
typedef struct { void* data; } IFC4X3_IfcBendingParameterSelect;
typedef struct { void* data; } IFC4X3_IfcBooleanOperand;
typedef struct { void* data; } IFC4X3_IfcClassificationReferenceSelect;
typedef struct { void* data; } IFC4X3_IfcClassificationSelect;
typedef struct { void* data; } IFC4X3_IfcColour;
typedef struct { void* data; } IFC4X3_IfcColourOrFactor;
typedef struct { void* data; } IFC4X3_IfcCoordinateReferenceSystemSelect;
typedef struct { void* data; } IFC4X3_IfcCsgSelect;
typedef struct { void* data; } IFC4X3_IfcCurveFontOrScaledCurveFontSelect;
typedef struct { void* data; } IFC4X3_IfcCurveMeasureSelect;
typedef struct { void* data; } IFC4X3_IfcCurveOnSurface;
typedef struct { void* data; } IFC4X3_IfcCurveOrEdgeCurve;
typedef struct { void* data; } IFC4X3_IfcCurveStyleFontSelect;
typedef struct { void* data; } IFC4X3_IfcDefinitionSelect;
typedef struct { void* data; } IFC4X3_IfcDerivedMeasureValue;
typedef struct { void* data; } IFC4X3_IfcDocumentSelect;
typedef struct { void* data; } IFC4X3_IfcFillStyleSelect;
typedef struct { void* data; } IFC4X3_IfcGeometricSetSelect;
typedef struct { void* data; } IFC4X3_IfcGridPlacementDirectionSelect;
typedef struct { void* data; } IFC4X3_IfcHatchLineDistanceSelect;
typedef struct { void* data; } IFC4X3_IfcInterferenceSelect;
typedef struct { void* data; } IFC4X3_IfcLayeredItem;
typedef struct { void* data; } IFC4X3_IfcLibrarySelect;
typedef struct { void* data; } IFC4X3_IfcLightDistributionDataSourceSelect;
typedef struct { void* data; } IFC4X3_IfcMaterialSelect;
typedef struct { void* data; } IFC4X3_IfcMeasureValue;
typedef struct { void* data; } IFC4X3_IfcMetricValueSelect;
typedef struct { void* data; } IFC4X3_IfcModulusOfRotationalSubgradeReactionSelect;
typedef struct { void* data; } IFC4X3_IfcModulusOfSubgradeReactionSelect;
typedef struct { void* data; } IFC4X3_IfcModulusOfTranslationalSubgradeReactionSelect;
typedef struct { void* data; } IFC4X3_IfcObjectReferenceSelect;
typedef struct { void* data; } IFC4X3_IfcPointOrVertexPoint;
typedef struct { void* data; } IFC4X3_IfcProcessSelect;
typedef struct { void* data; } IFC4X3_IfcProductRepresentationSelect;
typedef struct { void* data; } IFC4X3_IfcProductSelect;
typedef struct { void* data; } IFC4X3_IfcPropertySetDefinitionSelect;
typedef struct { void* data; } IFC4X3_IfcResourceObjectSelect;
typedef struct { void* data; } IFC4X3_IfcResourceSelect;
typedef struct { void* data; } IFC4X3_IfcRotationalStiffnessSelect;
typedef struct { void* data; } IFC4X3_IfcSegmentIndexSelect;
typedef struct { void* data; } IFC4X3_IfcShell;
typedef struct { void* data; } IFC4X3_IfcSimpleValue;
typedef struct { void* data; } IFC4X3_IfcSizeSelect;
typedef struct { void* data; } IFC4X3_IfcSolidOrShell;
typedef struct { void* data; } IFC4X3_IfcSpaceBoundarySelect;
typedef struct { void* data; } IFC4X3_IfcSpatialReferenceSelect;
typedef struct { void* data; } IFC4X3_IfcSpecularHighlightSelect;
typedef struct { void* data; } IFC4X3_IfcStructuralActivityAssignmentSelect;
typedef struct { void* data; } IFC4X3_IfcSurfaceOrFaceSurface;
typedef struct { void* data; } IFC4X3_IfcSurfaceStyleElementSelect;
typedef struct { void* data; } IFC4X3_IfcTextFontSelect;
typedef struct { void* data; } IFC4X3_IfcTimeOrRatioSelect;
typedef struct { void* data; } IFC4X3_IfcTranslationalStiffnessSelect;
typedef struct { void* data; } IFC4X3_IfcTrimmingSelect;
typedef struct { void* data; } IFC4X3_IfcUnit;
typedef struct { void* data; } IFC4X3_IfcValue;
typedef struct { void* data; } IFC4X3_IfcVectorOrDirection;
typedef struct { void* data; } IFC4X3_IfcWarpingStiffnessSelect;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* IFC_SCHEMA_H */
