// // Autogenerated Catch2 test suite based on the original TypeScript
// // specification Columns.spec.ts.  This file defines a single test
// // corresponding to the column example.  The test name and comment
// // match those of the original TypeScript test.  Since the C API
// // currently lacks the necessary functions to construct and stream
// // column geometry, the test body contains a TODO placeholder and
// // calls `SUCCEED()`.

// #include <catch2/catch_test_macros.hpp>
// #include <catch2/catch_approx.hpp>

// #include "web_ifc_api.h"

// // -----------------------------------------------------------------------------
// // Test the column example
// // -----------------------------------------------------------------------------

// TEST_CASE("Test the column example: Can we write the columns and read them back in") {
//     // test('Can we write the columns and read them back in ', async () => {
//     // TODO: implement creation of a 6x6 grid of columns, save the model,
//     // reopen it, stream all meshes and verify that 36 meshes are present.
//     SUCCEED("Placeholder for Can we write the columns and read them back in");
// }
